export const SET_USER_REQUEST = "SET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_ERROR = "GET_USER_ERROR"

export const SET_LOADING = "SET_LOADING"
export const SET_ERROR = "SET_ERROR"

export const GET_EXPENSE_REQUEST = "GET_EXPENSE_REQUEST"
export const GET_INCOME_REQUEST = "GET_INCOME_REQUEST"

export const ADD_EXPENSE_REQUEST = "ADD_EXPENSE_REQUEST"
export const ADD_INCOME_REQUEST = "ADD_INCOME_REQUEST"

export const UPDATE_EXPENSE_REQUEST = "UPDATE_EXPENSE_REQUEST"

export const DELETE_REQUEST = "DELETE_REQUEST"

export const CREATE_TRACKER = "CREATE_TRACKER"